# Generated by Django 2.1.3 on 2018-11-26 04:58

from django.db import migrations


def add_job_groups(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    job_group_model = apps.get_model("report", "jobgroup")
    job_group_model.objects.create(label="A", wage=20)
    job_group_model.objects.create(label="B", wage=30)

class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_job_groups, migrations.RunPython.noop),

    ]
