# Generated by Django 2.1.3 on 2018-11-26 03:49

from django.db import migrations, models

from payroll.report.helpers import get_pay_period_start_date


def set_pay_period_start_date(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    time_sheet_model = apps.get_model("report", "timesheet")

    for time_sheet in time_sheet_model.objects.all():
        time_sheet.pay_period_start_date = get_pay_period_start_date(time_sheet.date)
        time_sheet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20181126_0458'),
    ]


    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='pay_period_start_date',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(set_pay_period_start_date, migrations.RunPython.noop),
    ]
