version: '3'

services:
    db:
      image: "postgres:11"
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=dev
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=tilr_interview
      volumes:
        - ./data/postgres:/var/lib/postgresql/data

