# -*- coding: utf-8 -*-
"""Q2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QH2Iy4Hsk69hRtWQmaC75TLZeMTNf505
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# a) Load and clean the data
df_diva = pd.read_csv('diva-incstmt.csv', skiprows=5, usecols=[0, 1, 2, 3, 5])
df_divb = pd.read_csv('divb-incstmt.csv', skiprows=5, usecols=[0, 1, 2, 3, 5])
df_diva_cleaned = df_diva.dropna(subset=['Description']).reset_index(drop=True)
print(df_diva_cleaned)
df_divb_cleaned = df_divb.dropna(subset=['Description']).reset_index(drop=True)
print(df_divb_cleaned)

# Data composition for the stacked and clustered bar charts
df_sales_diva_cleaned = df_diva_cleaned[df_diva_cleaned['Description'] == 'Sales Revenue']
df_sales_divb_cleaned = df_divb_cleaned[df_divb_cleaned['Description'] == 'Sales Revenue']
years = ['Act2019', 'Act2020', 'Proj2021']
df_sales_combined_cleaned = pd.DataFrame({
    'Year': years,
    'Division A Sales': df_sales_diva_cleaned[years].values.flatten(),
    'Division B Sales': df_sales_divb_cleaned[years].values.flatten()
})

# b) Stacked Bar Chart
plt.figure(figsize=(6, 6))
plt.bar(df_sales_combined_cleaned['Year'], df_sales_combined_cleaned['Division A Sales'], color='green', label='Division A')
plt.bar(df_sales_combined_cleaned['Year'], df_sales_combined_cleaned['Division B Sales'], color= 'blue',
        bottom=df_sales_combined_cleaned['Division A Sales'], label='Division B')
plt.title('Stacked Bar Chart of Historical and Projected Sales Over Time')
plt.xlabel('Year')
plt.ylabel('Sales Revenue')
plt.legend()
plt.show()

# c) Clustered Bar Chart
df_sales_combined_cleaned.set_index('Year', inplace=True)
plt.figure(figsize=(6, 6))
df_sales_combined_cleaned.plot(kind='bar', stacked=False)
plt.title('Clustered Bar Chart of sales Over Time')
plt.xlabel('Year')
plt.ylabel('Sales Revenue')
plt.xticks(rotation=45)
plt.legend()
plt.show()

# d) Two separate Pie Charts
# Select the expense categories for 2021 forecasted
expense_categories = ['SGA', 'ADV', 'DEP', 'RENT', 'OTHX']
df_expenses_diva_2021 = df_diva_cleaned[df_diva_cleaned['CODE'].isin(expense_categories)].set_index('Description')['Proj2021']
df_expenses_divb_2021 = df_divb_cleaned[df_divb_cleaned['CODE'].isin(expense_categories)].set_index('Description')['Proj2021']

# Specify different colors for the pie chart segments
colors = ['yellow', 'green', 'pink', 'blue', 'orange']

# Create pie charts with specified colors
fig, ax = plt.subplots(1, 2, figsize=(12, 6))

# Pie chart for Division A
ax[0].pie(df_expenses_diva_2021, labels=df_expenses_diva_2021.index, autopct='%1.1f%%', startangle=140, colors=colors)
ax[0].set_title('Division A Expenses Forecasted for 2021')

# Pie chart for Division B
ax[1].pie(df_expenses_divb_2021, labels=df_expenses_divb_2021.index, autopct='%1.1f%%', startangle=140, colors=colors)
ax[1].set_title('Division B Expenses Forecasted for 2021')

plt.tight_layout()
plt.show()